/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { TestContract } from "./Test";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "Test"): TestContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { TestContract, TestInstance } from "./Test";
