
export { default as logo } from "./logo.png"
export { default as usdt } from "./usdt.png"
export { default as usdc } from "./usdc.png"
export { default as bnb } from "./bnb.png"
export { default as avax } from "./avax.png"
export { default as aave } from "./aave.png"
export { default as polygon } from "./polygon.png"
export { default as ether } from "./ether.png"
export { default as unknownTokenLogo } from "./unknownToken.png"
export { default as background } from "./background.jpg"
export { default as phone_bg } from "./phone-bg.jpg"
